### ISSUE TITLE
Drop use of frozendict as backing for ImmutableDict

### ISSUE THREAD

**Issue by rgabbard** [isi-vista/immutablecollections#32]
It only adds useless indirection.

**Comment by rgabbard** [comment]
Do https://github.com/isi-vista/immutablecollections/issues/27 (for dictionaries) first

**Comment by berquist** [comment]
@rgabbard Is this _only_ for `ImmutableDict`, or should it affect `_freeze_list_multidict` and `_freeze_set_multidict` as well?

**Comment by rgabbard** [comment]
Those as well - they should switch to using `ImmutableDict`
